my-app/src/App.css
=> small CSS change

README.md
=> UPDATED README FOR TEAM SYNERGY

README.md
=> added a line of text to README

my-app/src/Components/Homepage.js
=> removed unused imports/functions

my-app/.gitignore, my-app/package-lock.json, my-app/package.json, my-app/src/Components/Login.js, my-app/src/Components/Signup.js, my-app/src/Styles/Login.module.css, my-app/src/firebase.js
Saved authenticated users to firestore/retrieve user. Added Google sign in option too.
=> Saved auth users to db and added Google signin option, save to db

my-app/src/Components/Signup.js
Reverts csci-499-sp23/team-6-sp23-redux#54
=> Revert "env secrets added"

my-app/src/Components/Card.js, my-app/src/Components/CardDeck.js
Changes:
CardDeck.js : Keeping track of swipe direction in the console for test purposes
Card.js: Removed the strict x direction movement when dragging so users can swipe top-right, bottom-right etc.. Also added constraint values for smoother swiping
=> removed stiffness in swipe direction

my-app/src/Components/CardDeck.js, my-app/src/Components/Login.js, my-app/src/Components/Signup.js
Changes:
Login.js & Signup.js: Save the user's id in local storage for later use when referencing user data in other components
CardDeck.js: Save the hangout for the user on swipe to the firestore db
=> fixed conflict

my-app/src/Components/CardDeck.js, my-app/src/Services/HangoutService.js
Changes:
CardDeck.js: Properly shuffles deck on first load. Passes parameters of hangout categories and location to api fetch function for more dynamic fetching. The hardcoded values will be replaced by user's preferences in the future.
Saved swipes are organized by category in the database.
HangoutService.js: Added a category to each data retrieved based on the search term to later sort favorited places. Also made the code more dynamic and concise. Requires a location and passed in array of categories to fetch data.
=> Js hangout categories

my-app/src/Components/AppNavbar.js, my-app/src/Styles/AppNavbar.module.css
Changes:
Moved the login and signup button on the app navbar to the right and adjusted the font size.
=> adjusted the login and signup styling on the navbar

my-app/src/Components/Preferences.js
Preferences now has functionality for retrieving and updating a preferences field in firestore. 
File 1: Preferences.js 
Implementation of functions for retrieving preferences, which is implemented inside useEffect to trigger on page load.
Update Preferences button now updates the firebase doc for that user based on the currently toggled on buttons
=> Added retrieval and updating for categorial user preferences

my-app/src/Components/Preferences.js
Added userID into useEffect in Preferences.js to prevent compiler warning about dependencies
=> Added userID information into useEffect for dependency

my-app/src/Components/Preferences.js
The location button now takes the geolocation of the user and updates to firestore when Update Preferences is pressed. 
The two dropdown forms for location limit and yelp rating limit also add their information to firestore.
<Preferences.js>
Aforementioned changes of adding functionality
The preferencesMap global variable has been removed, as categorical preferences are now stored as an array of currently selected categories, making the map no longer necessary.
=> Added functionality to location button and the forms 

my-app/src/Components/App.js, my-app/src/Components/AppNavbar.js, my-app/src/Components/Login.js, my-app/src/Components/Profile.js, my-app/src/Components/Signup.js, my-app/src/Styles/Profile.module.css
Profile.js: Made a simple profile.js (to be updated more later with the css). The Profile component receives a `user` object as a prop and renders a profile page with the user's information. If the user object is not available, it displays a "Loading..." message.
App.js: made improvements to the App.js component to handle user authentication state more effectively by utilizing local storage. This ensures a better user experience as the application will now maintain the user's logged-in state across page refreshes and browser sessions.
AppNavBar.js: Updates the AppNavbar component to receive the `user` prop and conditionally render the `Profile`, `Login`, and `Signup` elements.
Signup.js: Added a new line to call the onSignup function, passing the `userData` as an argument. This will call …
=> Created a profile and added an authentication state

my-app/src/Components/App.js, my-app/src/Components/CardDeck.js, my-app/src/Components/Favoritelist.js, my-app/src/Components/HomepageWithCards.js, my-app/src/Components/Login.js, my-app/src/Components/Preferences.js, my-app/src/Services/UserService.js
Changes:
App.js: Includes event listen (onSnapshot) to capture updated user data in real time and saves them in states to pass to other components. Also added condition to prevent crash when user has not logged in and userId is unknown on app start.
Login.js & HomepageWithCards.js: Pseudo fixes navigation from login to homepage to display the rendered data after navigation by refreshing the page once after navigation.
=> added realtime update listener for user data

my-app/src/Components/App.js, my-app/src/Components/AppNavbar.js, my-app/src/Components/Profile.js, my-app/src/Styles/Profile.module.css
Changes/updates:
Used Firebase Authentication's listener for authentication state
Description:
I am updating the authentication state management in the app with Firebase Authentication's `onAuthStateChanged` listener.
Updates:
1. Updated the `useEffect` hook in `App.js` to use Firebase Authentication's `onAuthStateChanged` listener to set the `isAuthenticated` state.
2. Changed the `Profile` component route in `App.js` to use `auth.currentUser?.uid` as the `userId` prop.
3. Made a `Profile.js` with the css. Right now it displays the email of the logged in user. Will add more later on
Firebase Authentication's listener, ensures a more secure and scalable authentication system in our app.
=> Added authentication state/created profile

my-app/src/Components/App.js
Reverts csci-499-sp23/team-6-sp23-redux#78
=> Revert "variables"

my-app/src/Components/FavoriteCard.js, my-app/src/Components/Favoritelist.js, my-app/src/Styles/FavoriteCard.module.css, my-app/src/Styles/Favoritelist.module.css
Changes:
FavoriteList: Added user's favorite list information passed as props into a table with the first column containing the category and the remaining columns of the row containing the favorited hangout cards.
FavoriteCard: Component for all the cards displayed on FavoriteList
Also added some stylings to both component's modules
=> set up user's favorites hangout spots in a table with some styling

my-app/src/Components/Favoritelist.js, my-app/src/Styles/Favoritelist.module.css
Changes:
FavoriteList.js: Small changes to make the code neater and also fix the error of having a td nested in a div. Changed the table to have 2 columns per row and the 2nd column contains a scrollable div containing the list of favorite hangout spots.
FavoriteList.css: Updated the styling and made the horizontal scroll bar orange to match app theme
=> clean up makeTable function and styling

my-app/src/Components/App.js, my-app/src/Components/CardDeck.js, my-app/src/Components/HomepageWithCards.js
Changes:
App.js: passed favorites to homepage w/ cards to then pass to CardDeck.js
CardDeck.js: Uses favorite hangout locations prop to filter the search for locations and prevent users from seeing duplicates of locations they already liked
=> added filter to prevent liking dupes

my-app/src/Components/FavoriteCard.js, my-app/src/Components/FavoriteDetails.js, my-app/src/Components/Favoritelist.js, my-app/src/Styles/FavoriteModal.module.css
Changes:
New Modal Component for Favorites: Implemented Modal Box that displays information for each Favorites Hangout. Basic CSS has been applied as well.
Favorites list: Hangout Details and Ratings have been added as additional attributes passed to Favorite Card Component.
=> Modal for Favorites implemented

.github/workflows/firebase-hosting-merge.yml, .github/workflows/firebase-hosting-pull-request.yml, my-app/.gitignore, my-app/package-lock.json, my-app/src/Components/FavoriteDetails.js
Untracked .env, updated yml to create the .env and use environment secrets during the workflow.
=> Updated yml

.github/workflows/firebase-hosting-merge.yml, .github/workflows/firebase-hosting-pull-request.yml
Testing to see if the workflow is fixed, by adding extra steps
=> Workflow update

.github/workflows/firebase-hosting-merge.yml, .github/workflows/firebase-hosting-pull-request.yml
Reverts csci-499-sp23/team-6-sp23-redux#89
=> Revert "Workflow update"

.github/workflows/firebase-hosting-merge.yml, .github/workflows/firebase-hosting-pull-request.yml, my-app/.gitignore, my-app/package-lock.json, my-app/src/Components/FavoriteDetails.js
Reverts csci-499-sp23/team-6-sp23-redux#88
=> Revert "Updated yml"

my-app/package-lock.json, my-app/package.json
Trying to resolve error by removing package-lock.json and node modules and npm install again
=> Trying to resolve error

my-app/src/Components/App.js, my-app/src/Components/AppNavbar.js, my-app/src/Components/Login.js, my-app/src/Components/Preferences.js, my-app/src/Components/Profile.js, my-app/src/Components/ProfilePage/AvatarUpload.jsx, my-app/src/Components/ProfilePage/UpdatePassword.jsx, my-app/src/Components/ProfilePage/UpdateUsername.jsx, my-app/src/Components/ProfilePage/UserInfo.jsx, my-app/src/Components/Signup.js, my-app/src/Styles/Profile.module.css, my-app/src/firebase.js
Added firebase storage to `firebase.js`
`UpdateUsername.jsx`: user can now update their username but by default the email excluding the @ symbol is used as username on signup.  User can update this in profile.
User location is set on signup, with 3 categories set on default. If location is denied, the user won't be allowed to sign up
Added an Avartar in AppNavBar to display the users current avartar and also have a drop down menu for the user to either go to their profile or logout.
=> User location and preferences set on signup

my-app/src/Components/App.js, my-app/src/Components/Profile.js, my-app/src/Components/ProfilePage/UpdateUsername.jsx
Changes:
App.js: Pass the user information the profile
Profile: Fix how user information was being collected and fixed the update user form to update the username without refreshing and fixed the error when an invalid username is set
=> fixed update username in profile

my-app/src/Components/App.js, my-app/src/Components/Preferences.js, my-app/src/Styles/Preferences.module.css, my-app/src/Styles/Profile.module.css, my-app/src/firebase.js
Files Changed:
App.js: Changed the landing page based on whether the user is logged into firebase or not. If logged in then they land on the card page otherwise they land on the login page. (User may persist log in state until they sign out or switch to a different browser/device)
Preferences: Added a popup view that appears when the user updates their preferences to notify the user that they saved their changes successfully. The view will disappear after 2 seconds.
=> added saved preferences animation

my-app/src/Components/App.js, my-app/src/Components/CardDeck.js, my-app/src/Components/HomepageWithCards.js, my-app/src/Components/Preferences.js, my-app/src/Components/Signup.js, my-app/src/Styles/Preferences.module.css
<HomepageWithCards.js> Passes ratingLimit to CardDeck
<CardDeck.js> Now filters the cards using the yelp rating limit specified by the user
<Preferences.js> Now displays the user's username at the top, 11 additional categories have been added for variety, yelp rating limits have been adjusted to use more practical thresholds. CSS slightly adjusted for this page
<Signup.js> simple change to ratingLimit being default 0 now, no functional difference.
=> Added Yelp rating filter functionality, and some CSS on preferences

my-app/src/Components/Login.js, my-app/src/Components/Signup.js, my-app/src/Styles/Login.module.css
Login screen styling updated.
Screenshot below:
=> Login Style updated

my-app/src/Components/App.js, my-app/src/Components/Profile.js, my-app/src/Components/ProfilePage/AvatarUpload.jsx, my-app/src/Components/ProfilePage/UpdatePassword.jsx, my-app/src/Components/ProfilePage/UserInfo.jsx, my-app/src/Styles/Profile.module.css
Changes:
App.js: Pass the location state to Profile
Avatar_Upload.jsx: Fixed the image upload to firebase storage and setting the image to the profile image tag
UserInfo.jsx: Fixed the parsing for the user location using the google maps api and passed location props. Separated the latitude and longitude values from the props value. Also sets the image for the user profile from firebase storage if it exists. 
UpdatePassword.jsx: Changed the confirm password field to confirm the new password instead of current
=> Js profile

my-app/src/Components/FavoriteCard.js
Simple change for firebase deployment
=> Added triple equal sign

my-app/src/Components/AppNavbar.js, my-app/src/Styles/AppNavbar.module.css
Changes:
AppNavbar.js: Updated styling for the profile dropdown by adding the user's username and a dropdown arrow. Also adjusted the dropdown menu color on hover
=> updated styling of profile dropdown in navbar

my-app/src/Components/CardDeck.js, my-app/src/Components/EmptyDeck.js, my-app/src/Styles/CardDeck.module.css
<CardDeck.js> Now has a state for loading that is used to display a loading spinner
<EmptyDeck.js> button for empty deck display now enables the loading state
=> Added loading spinner while waiting for the fetch requests

my-app/src/Components/FavoriteCard.js, my-app/src/Components/FavoriteDetails.js, my-app/src/Components/Favoritelist.js, my-app/src/Styles/FavoriteCard.module.css, my-app/src/Styles/FavoriteModal.module.css, my-app/src/Styles/Favoritelist.module.css
Changes:
FavoriteList & Favorite Card: Fixed the favorite card deleting the wrong card in the array. Fixed scrollbar not scrolling when there is a horizontal overflow. Sorted the favorite list display alphabetically. Updated favorite list styling to be consistent with the rest of the website.
=> FavoriteList Style changes for cards and fixed bugs

my-app/src/Components/ForgotPassword.js, my-app/src/Components/Login.js, my-app/src/Components/Signup.js, my-app/src/Styles/Login.module.css
Updated the login style and the signup style to be more clean and appealing. Added some more user friendly features to reveal or hide passwords when logging in or signing up.
=> Updated login and signup style

my-app/src/Components/Preferences.js, my-app/src/Components/SubComponents/Alert.js, my-app/src/Styles/Alert.module.css, my-app/src/Styles/Preferences.module.css
Changes:
Preferences.js: Updated the styling of the location search bar and added a hover identifier to the geolocator button and search icon. Also made the search locations bar based on the user pressing enter.
Alert.js: Made a view for alert messages when searching because using alert() freezes the website until the user presses okay.
=> Js preferences

my-app/src/Components/FavoriteDetails.js, my-app/src/Components/Favoritelist.js, my-app/src/Styles/FavoriteModal.module.css
FavoritesDetails: Just added the clipboard feature to the URL for each favorites in the modal.
=> Small Clipboard Changes before demo

my-app/src/Components/Favoritelist.js, my-app/src/Styles/Favoritelist.module.css
Changes:
FavoriteList.js: Added event listeners to detect when the category row is hovered and then made the overflow draggable instead of the user relying on the scrollbar. Also added a state variable to determine when the user is dragging to prevent the modal from favorite cards appearing on drag.
=> made the favorite list overflow draggable instead of using a scrollbar

my-app/src/Components/AppNavbar.js, my-app/src/Styles/AppNavbar.module.css
Changes:
AppNavbar.js: Hide the Navbar Toggle component when the user clicks on it. This component is only visible on smaller screens such as mobile devices. Adjusted the sizes of the routes and logo for portrait and landscape modes.
=> make navbar more responsive for different screens

my-app/src/Components/Favoritelist.js, my-app/src/Styles/App.css, my-app/src/Styles/FavoriteCard.module.css, my-app/src/Styles/FavoriteModal.module.css, my-app/src/Styles/Favoritelist.module.css
Changes:
FavoriteList.js: Converted the tables into flexbox divs for more flexible and stylish views for the cards as well as cleaner looking code. Added swipe (onTouch) events for mobile users. Also adjusted the styling of the cards on favoritelist to be more responsive for mobile users.
FavoriteModal & FavoriteCard.css: Added a hover state that changes the color/opacity for the favorite card and delete buttons for a better use experience.
=> Js flextable2

my-app/src/Styles/Profile.module.css
Changes: 
Profile.module.css: Added media queries to make the profile page more responsive on smaller sized devices for both landscape and portrait orientation. Added another media query for landscape mobile devices to avoid adjusting the desktop design.
=> add changes to make profile page more responsive

my-app/src/Components/Card.js, my-app/src/Components/CardDeck.js, my-app/src/Components/FavoriteDetails.js, my-app/src/Components/Favoritelist.js, my-app/src/Components/HangoutDetail.js, my-app/src/Components/SwipeableCard.js, my-app/src/Styles/Card.module.css, my-app/src/Styles/FavoriteCard.module.css
Homepage: In preparation for details implementation, I used the one done in favorite by Jordan and I. Same functionality as the favorites.
CardDeck: Had to add URL for the clipboard implementation I did for homepage as something passed via props.
=> Implemented Modal from Favorites onto homepage in prep

my-app/src/Components/FavoriteDetails.js, my-app/src/Components/HangoutDetail.js
Reverts csci-499-sp23/team-6-sp23-redux#142,
had some unused variables that needed to be removed.
=> Resolved unused conflicts

my-app/src/Components/App.js, my-app/src/Components/Card.js, my-app/src/Components/CardDeck.js, my-app/src/Components/FavoriteCard.js, my-app/src/Components/Favoritelist.js, my-app/src/Components/SwipeableCard.js, my-app/src/Services/LikesService.js
Changes:
LikesService.js: Added an async function to fetch the number of likes data 
Card.js & FavoriteCard.js: Retrieve the number of likes 
CardDeck.js: Added new document reference for hangouts when the card is swiped it keeps track of the userid of the user that liked it
FavoriteCard.js: Deletes user from the hangout's # of likes array when the user deletes the hangout
=> added number of likes to each hangout

my-app/src/Styles/FavoriteCard.module.css
Changes: 
FavoriteCard.css: Adjusted the width and height for the mobile view of the delete button to be more responsive
=> adjusted delete button for mobile

my-app/src/Components/App.js, my-app/src/Components/Card.js, my-app/src/Components/HomepageWithCards.js, my-app/src/Styles/App.css, my-app/src/Styles/AppNavbar.module.css, my-app/src/Styles/Card.module.css, my-app/src/Styles/CardDeck.module.css, my-app/src/Styles/Homepage.module.css
Changes:
App.js: Modified the layout of the app views to have the navbar stick to the top while the rest of the app routes are scrollable.
CardDeck.js: Added a styling container for the card deck on the homepage.
Card.js: Changed the styling on the card to apply to the card instead of the tinder card. Also made it more responsive for mobile devices.
=> made navbar stick to the top on scroll

my-app/src/Components/CardDeck.js
Changes:
CardDeck.js: Updated the remove card function to not directly mutate the hangoutData state
=> Js carddeck

my-app/src/Components/SubComponents/SwipeFeedback.js, my-app/src/Components/SwipeableCard.js, my-app/src/Styles/SwipeFeedback.module.css
Changes:
SwipeFeedback.js: A component that renders a view for feedback to the user on when a card is swiped left or right. Messages are randomly chosen within an array of messages.
SwipeableCard.js: Included a state to render the view of SwipeFeedback depending on when a card is swiped left or right. After 1.5 seconds the next card will appear. The time can be adjusted. Also the state will be automatically set to the default case of false once the next card renders so it is not necessary to set the state back to false.
=> added a feedback view for swiped cards

my-app/package-lock.json, my-app/package.json
Fixed google maps import issue on previous failed merged code.
=> Fixed Google maps deploy imports

my-app/src/Components/Signup.js, my-app/src/Styles/App.css, my-app/src/Styles/Login.module.css
Fixed styling for the password box in signup and login so that the error message appears under. Files changed:
Signup.js - Added appropriate classname in order to add styling App.css- added styling for class name .error-message because it wasnt there before Login.module.css - Added styling in order to make the forms look better.
=> fixed cs styling for password

my-app/src/Components/Favoritelist.js, my-app/src/Styles/Favoritelist.module.css
Changes:
Fix the slider touch event to account for vertical swipes
=> updated swiping for favoritelist

my-app/src/Components/Login.js, my-app/src/Styles/Login.module.css
Changes:
Updated the password toggle for the login page to be inside the input field and removed the extra unecessary margins
=> fix the login page styling error
